export const FETCH_ALL_DATA_REQUEST = "FETCH_ALL_DATA_REQUEST"
export const FETCH_ALL_DATA_SUCCESS = "FETCH_ALL_DATA_SUCCESS"
export const FETCH_ALL_DATA_FAIL = "FETCH_ALL_DATA_FAIL"

export const FETCH_SINGLE_DATA_REQUEST = "FETCH_SINGLE_DATA_REQUEST"
export const FETCH_SINGLE_DATA_SUCCESS = "FETCH_SINGLE_DATA_SUCCESS"
export const FETCH_SINGLE_DATA_FAIL = "FETCH_SINGLE_DATA_FAIL"